// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/bookmark/bookmark_service.proto

// unique package names as the path, / => .

package bookmark

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_bookmark_bookmark_service_proto protoreflect.FileDescriptor

const file_api_bookmark_bookmark_service_proto_rawDesc = "" +
	"\n" +
	"#api/bookmark/bookmark_service.proto\x128github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark\x1a\x1bapi/bookmark/messages.proto2\xf3\x02\n" +
	"\bBookmark\x12\xb3\x01\n" +
	"\x0eCreateBookmark\x12O.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkRequest\x1aP.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkResponse\x12\xb0\x01\n" +
	"\rListBookmarks\x12N.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksRequest\x1aO.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksResponseB\xea\x02\n" +
	"<com.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmarkB\x14BookmarkServiceProtoP\x01Z\x10pkg/api/bookmark\xa2\x02\x06GLGPAB\xaa\x027Github.Llamaunicorn.GrpcBookmarks.Protobuf.Api.Bookmark\xca\x027Github\\Llamaunicorn\\GrpcBookmarks\\Protobuf\\Api\\Bookmark\xe2\x02CGithub\\Llamaunicorn\\GrpcBookmarks\\Protobuf\\Api\\Bookmark\\GPBMetadata\xea\x02<Github::Llamaunicorn::GrpcBookmarks::Protobuf::Api::Bookmarkb\x06proto3"

var file_api_bookmark_bookmark_service_proto_goTypes = []any{
	(*CreateBookmarkRequest)(nil),  // 0: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkRequest
	(*ListBookmarksRequest)(nil),   // 1: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksRequest
	(*CreateBookmarkResponse)(nil), // 2: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkResponse
	(*ListBookmarksResponse)(nil),  // 3: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksResponse
}
var file_api_bookmark_bookmark_service_proto_depIdxs = []int32{
	0, // 0: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.Bookmark.CreateBookmark:input_type -> github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkRequest
	1, // 1: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.Bookmark.ListBookmarks:input_type -> github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksRequest
	2, // 2: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.Bookmark.CreateBookmark:output_type -> github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkResponse
	3, // 3: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.Bookmark.ListBookmarks:output_type -> github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bookmark_bookmark_service_proto_init() }
func file_api_bookmark_bookmark_service_proto_init() {
	if File_api_bookmark_bookmark_service_proto != nil {
		return
	}
	file_api_bookmark_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bookmark_bookmark_service_proto_rawDesc), len(file_api_bookmark_bookmark_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bookmark_bookmark_service_proto_goTypes,
		DependencyIndexes: file_api_bookmark_bookmark_service_proto_depIdxs,
	}.Build()
	File_api_bookmark_bookmark_service_proto = out.File
	file_api_bookmark_bookmark_service_proto_goTypes = nil
	file_api_bookmark_bookmark_service_proto_depIdxs = nil
}
