// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/bookmark/messages.proto

package bookmark

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBookmarkRequest request for bookmark creation
type CreateBookmarkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title of a bookmark
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// url of a bookmark
	// TODO Add validation
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// TODO Add enum style field
	Tag           string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookmarkRequest) Reset() {
	*x = CreateBookmarkRequest{}
	mi := &file_api_bookmark_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkRequest) ProtoMessage() {}

func (x *CreateBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookmark_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkRequest.ProtoReflect.Descriptor instead.
func (*CreateBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_api_bookmark_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookmarkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookmarkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateBookmarkRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// CreateBookmarkResponse response for bookmark creation
type CreateBookmarkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bookmark_id id of a created bookmark
	BookmarkId    uint64 `protobuf:"varint,1,opt,name=bookmark_id,json=bookmarkId,proto3" json:"bookmark_id,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookmarkResponse) Reset() {
	*x = CreateBookmarkResponse{}
	mi := &file_api_bookmark_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkResponse) ProtoMessage() {}

func (x *CreateBookmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookmark_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkResponse.ProtoReflect.Descriptor instead.
func (*CreateBookmarkResponse) Descriptor() ([]byte, []int) {
	return file_api_bookmark_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookmarkResponse) GetBookmarkId() uint64 {
	if x != nil {
		return x.BookmarkId
	}
	return 0
}

type ListBookmarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksRequest) Reset() {
	*x = ListBookmarksRequest{}
	mi := &file_api_bookmark_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksRequest) ProtoMessage() {}

func (x *ListBookmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookmark_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksRequest.ProtoReflect.Descriptor instead.
func (*ListBookmarksRequest) Descriptor() ([]byte, []int) {
	return file_api_bookmark_messages_proto_rawDescGZIP(), []int{2}
}

type ListBookmarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksResponse) Reset() {
	*x = ListBookmarksResponse{}
	mi := &file_api_bookmark_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksResponse) ProtoMessage() {}

func (x *ListBookmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookmark_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksResponse.ProtoReflect.Descriptor instead.
func (*ListBookmarksResponse) Descriptor() ([]byte, []int) {
	return file_api_bookmark_messages_proto_rawDescGZIP(), []int{3}
}

var File_api_bookmark_messages_proto protoreflect.FileDescriptor

const file_api_bookmark_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/bookmark/messages.proto\x128github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark\"Q\n" +
	"\x15CreateBookmarkRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"9\n" +
	"\x16CreateBookmarkResponse\x12\x1f\n" +
	"\vbookmark_id\x18\x01 \x01(\x04R\n" +
	"bookmarkId\"\x16\n" +
	"\x14ListBookmarksRequest\"\x17\n" +
	"\x15ListBookmarksResponseB\xe3\x02\n" +
	"<com.github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmarkB\rMessagesProtoP\x01Z\x10pkg/api/bookmark\xa2\x02\x06GLGPAB\xaa\x027Github.Llamaunicorn.GrpcBookmarks.Protobuf.Api.Bookmark\xca\x027Github\\Llamaunicorn\\GrpcBookmarks\\Protobuf\\Api\\Bookmark\xe2\x02CGithub\\Llamaunicorn\\GrpcBookmarks\\Protobuf\\Api\\Bookmark\\GPBMetadata\xea\x02<Github::Llamaunicorn::GrpcBookmarks::Protobuf::Api::Bookmarkb\x06proto3"

var (
	file_api_bookmark_messages_proto_rawDescOnce sync.Once
	file_api_bookmark_messages_proto_rawDescData []byte
)

func file_api_bookmark_messages_proto_rawDescGZIP() []byte {
	file_api_bookmark_messages_proto_rawDescOnce.Do(func() {
		file_api_bookmark_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bookmark_messages_proto_rawDesc), len(file_api_bookmark_messages_proto_rawDesc)))
	})
	return file_api_bookmark_messages_proto_rawDescData
}

var file_api_bookmark_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_bookmark_messages_proto_goTypes = []any{
	(*CreateBookmarkRequest)(nil),  // 0: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkRequest
	(*CreateBookmarkResponse)(nil), // 1: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.CreateBookmarkResponse
	(*ListBookmarksRequest)(nil),   // 2: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksRequest
	(*ListBookmarksResponse)(nil),  // 3: github.llamaunicorn.grpc_bookmarks.protobuf.api.bookmark.ListBookmarksResponse
}
var file_api_bookmark_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bookmark_messages_proto_init() }
func file_api_bookmark_messages_proto_init() {
	if File_api_bookmark_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bookmark_messages_proto_rawDesc), len(file_api_bookmark_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_bookmark_messages_proto_goTypes,
		DependencyIndexes: file_api_bookmark_messages_proto_depIdxs,
		MessageInfos:      file_api_bookmark_messages_proto_msgTypes,
	}.Build()
	File_api_bookmark_messages_proto = out.File
	file_api_bookmark_messages_proto_goTypes = nil
	file_api_bookmark_messages_proto_depIdxs = nil
}
